name: Fetch and Commit Options Data

# Puedes descomentar schedule si quieres que corra automáticamente cada 12 h:
# on:
#   schedule:
#     - cron: '0 */12 * * *'
on:
  workflow_dispatch:

jobs:
  fetch-options:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch options data
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: |
          # Ejecuta main.py como módulo para que las importaciones relativas funcionen
          python -m main --db options_data.db --interval 15

      - name: Commit updated DB
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add options_data.db
          git commit -m "Auto‑update options_data.db" || echo "No changes to commit"
          git push
