name: Fetch and Commit Options Data

on:
  workflow_dispatch:
  # Uncomment to run every 12h:
  # schedule:
  #   - cron: '0 */12 * * *'

jobs:
  fetch-options:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch options data
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: |
          python -m main --db options_data.db --interval 15 --once

      - name: Commit updated DB
        run: |
          # Disable the “ignored file” warning
          git config advice.addIgnoredFile false
          # Force-add the DB even if it's in .gitignore
          git add -f options_data.db
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Auto‑update options_data.db" || echo "No changes to commit"
          git push
