name: Fetch and Commit Options Data

# 1) Give the GITHUB_TOKEN write access to the repo’s contents
permissions:
  contents: write

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */12 * * *'

jobs:
  fetch-options:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # 2) Make sure the GITHUB_TOKEN credentials are kept on the checkout
          persist-credentials: true

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch options data
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: |
          python -m main --db options_data.db --interval 15 --once

      - name: Commit updated DB
        run: |
          # Suppress “ignored by .gitignore” warnings
          git config advice.addIgnoredFile false
          # Force-add even if it's in .gitignore
          git add -f options_data.db
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Auto‑update options_data.db" || echo "No changes to commit"
          git push
