name: Fetch and Commit Options Data

# Dar permiso de escritura al token de GitHub Actions
permissions:
  contents: write

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */12 * * *'

jobs:
  fetch-options:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug—check POLYGON_API_KEY
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: |
          if [ -z "$POLYGON_API_KEY" ]; then
            echo "❌ POLYGON_API_KEY is empty! Define it in Settings → Secrets → Actions"
            exit 1
          else
            echo "✅ POLYGON_API_KEY loaded (length ${#POLYGON_API_KEY})"
            echo "   Starts: ${POLYGON_API_KEY:0:4}… Ends: ${POLYGON_API_KEY: -4}"
          fi

      - name: Fetch options data
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: |
          python -m main --db options_data.db --interval 15 --once

      - name: Commit updated DB
        run: |
          git config advice.addIgnoredFile false
          git add -f options_data.db
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Auto‑update options_data.db" || echo "No changes to commit"
          git push
