name: Update options data

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Run data fetcher
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: |
          timeout 3600 python -m main --db options_data.db --interval 15
      - name: Commit database
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add options_data.db
          git commit -m "Update options data" || echo "No changes to commit"
          git push
