name: Update options data

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r options-dashboard/requirements.txt
      - name: Run data updater
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: |
          # Install yfinance (in case not available)
          python -m pip install yfinance
          # Run the updater for 1 hour to populate the database
          timeout 3600 python options-dashboard/main.py --db options-dashboard/options_data.db --interval 15
      - name: Commit and push updated database
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add options-dashboard/options_data.db
          if ! git diff --cached --quiet; then
            git commit -m "Update options data [ci skip]"
            git push
          else
            echo "No changes to commit."
